// ANTICHEAT SCRIPT GENERATED BY CHATGPT
// (I have no idea how to write something like this)

// This script is currently not being used

const TAB_ID = crypto.randomUUID();
const LOCK_KEY = "game_lock";

function getLock() {
    return JSON.parse(localStorage.getItem(LOCK_KEY));
}

function setLock(data) {
    localStorage.setItem(LOCK_KEY, JSON.stringify(data));
}

const now = Date.now();
const lock = getLock();

if (!lock || now - lock.lastSeen > 3000) {
    // No lock or stale lock
    setLock({ owner: TAB_ID, lastSeen: now });
} else if (lock.owner !== TAB_ID) {
    // alert("Game already open in another tab.");
    document.body.innerHTML = "<div class=\"anticheat\"><h1>Something went wrong while loading the form. :(</h1><p>You can only have one form open at a time.</p></dov>";
    throw new Error("Locked");
}

setInterval(() => {
    const lock = getLock();
    if (lock?.owner === TAB_ID) {
        setLock({ owner: TAB_ID, lastSeen: Date.now() });
    }
}, 1000);

window.addEventListener("beforeunload", () => {
    const lock = getLock();
    if (lock?.owner === TAB_ID) {
        localStorage.removeItem(LOCK_KEY);
    }
});

window.addEventListener("storage", (e) => {
    if (e.key === LOCK_KEY) {
        const lock = getLock();
        if (lock?.owner !== TAB_ID) {
            alert("Another instance took over the game.");
            location.reload();
        }
    }
});